import React from "react";
import InputPanel from "./InputPanel";

export default function Dashboard({
  onAnalyze, onFileUpload, loading, error,
  showAiSettings, setShowAiSettings,
  aiApiKey, setAiApiKey,
}) {
  return (
    <div>
      <div className="card" style={{ marginBottom: 20 }}>
        <p style={{ fontSize: "0.9rem", color: "var(--text-secondary)", lineHeight: 1.6 }}>
          This tool analyzes writing patterns to estimate the likelihood that a text
          was generated by AI, written by a human, or is a mixture of both. Analysis
          is based on statistical linguistic features and is <strong>probabilistic,
          not conclusive</strong>. Results should never be used as definitive proof
          of authorship.
        </p>
      </div>

      <InputPanel
        onAnalyze={onAnalyze}
        onFileUpload={onFileUpload}
        loading={loading}
        showAiSettings={showAiSettings}
        setShowAiSettings={setShowAiSettings}
        aiApiKey={aiApiKey}
        setAiApiKey={setAiApiKey}
      />

      {error && (
        <div
          className="card"
          style={{
            borderLeft: "4px solid var(--danger)",
            color: "var(--danger)",
            fontSize: "0.9rem",
          }}
        >
          {error}
        </div>
      )}

      {loading && (
        <div className="loading-spinner">
          <div className="spinner" />
          <span>Analyzing writing patterns...</span>
        </div>
      )}

      <div className="card" style={{ marginTop: 20 }}>
        <h3 className="card-title">How It Works</h3>
        <div style={{ fontSize: "0.85rem", color: "var(--text-secondary)", lineHeight: 1.7 }}>
          <p style={{ marginBottom: 8 }}>
            <strong>Research Foundation:</strong> The detector evaluates 14 linguistic
            indicators derived from peer-reviewed research on AI-generated text detection
            (Guo et al. 2023; Mitchell et al. 2023; Tulchinskii et al. 2023;
            Sadasivan et al. 2023; Liang et al. 2024).
          </p>
          <p style={{ marginBottom: 8 }}>
            <strong>What We Analyze:</strong> Sentence length variation, lexical
            diversity, repetition patterns, transition word choices, paragraph
            structure uniformity, personal voice markers, hedging language,
            evidence specificity, readability profiles, and semantic similarity
            between paragraphs.
          </p>
          <p style={{ marginBottom: 8 }}>
            <strong>Important Limitations:</strong> Succinct formal writing,
            non-native English, writing under strict templates, and certain
            academic genres can produce false positives. AI-assisted editing
            (e.g., Grammarly, ChatGPT polish) is nearly indistinguishable from
            fully AI-generated text in many cases.
          </p>
          <p>
            <strong>Supported formats:</strong> Paste text directly, or upload
            .txt, .docx, or .pdf files. Minimum 20 characters recommended for
            meaningful analysis.
          </p>
        </div>
      </div>
    </div>
  );
}
